[package]
name = "vidyut"
version = "0.1.0"
edition = "2021"
author = "Ajay Kumar <iajkumar1205@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.2", features = ["full"] }
